### ISSUE TITLE
Document maximum number of days

### ISSUE THREAD

**Issue by Bibo-Joshi** [stw-on/api-docs#1]
Hi! Thanks for the neat documentation of the new API. I really like it :)
When trying it out, I noticed that requesting the menu of too many days at once, you'll get a response

```
{"error":{"code":400,"message":"Cannot query more than 21 days at once"}}
```
and wanted to ask if maybe that could be added to the documentation.

Kind regards,
Bibo-Joshi

**Comment by timoschwarzer** [comment]
Hi!

Thank you for your kind words :)
I've added a note with c9a6086db5cd2de5769edfac364d726077ceeb6b. Should be deployed in a few minutes...
