### ISSUE TITLE
Docs of special_tags and unexpected API responses

### ISSUE THREAD

**Issue by Bibo-Joshi** [stw-on/api-docs#2]
Hi there,

I noticed that the documentation is not very precise about the format of the `special_tags`. Maybe that could be added?

From the current documentation I would have assumed that they are in the same format as the other tags (`id` and `name`), but looking at the menu for january, I sometimes see (apart from empty special tags)

```python
"special_tags": [
  "-"
]
```
or even

```python
"special_tags": [
  "-",
  " -"
]
```
so I guess special tags are plain strings, though above output seems a bit strange to me (if the meal is not special, why put the `"-"`?). If this is a bug, I would be happy for a fix :)

**Comment by Bibo-Joshi** [comment]
I found a second unexpected response: `https://sls.api.stw-on.de/v1/location/105/menu/2021-01-15?time=noon` gives

```
{
  "announcements": [],
  "meals": [
    {
      "id": 10947,
      "date": "2021-01-15",
      "name": "Aufgrund der Coronakrise bleibt diese Einrichtung geschlossen. Wir bieten Euch Speisen in unserer Cafeteria im Au\\u00dfer-Haus-Verkauf an!",
      "price": {
        "student": "0.00",
        "employee": "0.00",
        "guest": "0.00"
      },
      "location": {...
        },
        "opening_hours": [...]
      },
      "time": "noon",
      "lane": {... },
      "tags": {...},
      "special_tags": []
    },
    ...
  ]
}
```
while I would certainly expect for this announcement to be in the announcements field and not listed as a meal.

**Comment by timoschwarzer** [comment]
@Bibo-Joshi Hi! The first one is a bug and will likely be fixed in the new year. The second one is intentional because currently, many clients don't parse or display the announcements in their apps and printouts which is why we decided to add this message as a meal for now so everyone can see it.

**Comment by Bibo-Joshi** [comment]
Hi, thinks for the quick response! Fair enough, I took my time to upgrade, too :D But it would still be nice to have the announcement in the corresponding field *additionally*, so that clients already parsing the announcements can profit from them.

Looking forword to the fix for special tags!

Also I noticed that the menu for of the Bistro4u on 2021-01-11 (`https://sls.api.stw-on.de/v1/location/109/menu/2021-01-11?time=noon`) contains a lot of duplicate meals (for some reason they have different IDs, though …). However that problem seems to only occur on that day. Just FYI as I'm already typing anyway …

**Comment by timoschwarzer** [comment]
> Also I noticed that the menu for of the Bistro4u on 2021-01-11 (`https://sls.api.stw-on.de/v1/location/109/menu/2021-01-11?time=noon`) contains a lot of duplicate meals

Looking at https://www.stw-on.de/braunschweig/essen/mensen-cafeterien/bistro4u/ it seems like this was not a problem with the API but rather with the management application. Thanks for reporting, we'll investigate this.

> But it would still be nice to have the announcement in the corresponding field _additionally_

I'll forward that :)

**Comment by timoschwarzer** [comment]
Closing this as it's considered fixed in the upcoming version.
