### ISSUE TITLE
Replacement for old XML API

### ISSUE THREAD

**Issue by yschroeder** [stw-on/api-docs#3]
The deprecated XML API recently stopped working. However, we have an application that processes this "full dump" that was available via the XML API. The JSON API has no means of providing this full dump of everything (this might be intentional).

However, I would still like to ask if it is possible to add an API endpoint that dumps everything as the XML API did (in JSON format of course).

May I suggest that calling `GET` on `https://sls.api.stw-on.de/v1` (without a location) returns the full dump as the XML API did? As this data set would have multiple hundreds of kilobytes, it would also be fine if a more severe rate limiting is imposed here.

**Comment by timoschwarzer** [comment]
Hi Yannic, thanks for the suggestion. :)

There's now an endpoint available at https://sls.api.stw-on.de/v1/meals
