### ISSUE TITLE
Server error for API url

### ISSUE THREAD

**Issue by JonasDix** [stw-on/api-docs#4]
Hi there,

since last week Tuesday, sadly I cannot load the api url "https://sls.api.stw-on.de/v1/meals" due to a "Internal server error - 500". 

It would be great if it could be fixed. Is there a possibility to get access to the data from last week? 

Thanks a lot,
Jonas

**Comment by timoschwarzer** [comment]
@JonasDix thanks for reporting! I fixed that endpoint just now.

~~To fetch the data from last week either use that endpoint or query the time span specifically for each canteen using this endpoint: https://api.stw-on.de/#mehrere-tagesmenus~~

Edit: I just noticed that we don't keep historical data around in the API, so unfortunately there's no easy way for me to get the data for you in the same machine readable format.

**Comment by JonasDix** [comment]
@timoschwarzer Thanks a lot for fixing!
